services:
  nginx:
    container_name: nginx-reborn
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - network-reborn

  app:
    image: spring-reborn:latest
    container_name: spring-reborn
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - network-reborn

  postgres:
    container_name: postgres-reborn
    build:
      context: ./db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - network-reborn

  mosquitto:
    container_name: mosquitto-reborn
    build:
      context: ./mqtt
    ports:
      - "8883:8883"
    networks:
      - network-reborn

networks:
  network-reborn:

volumes:
  postgres-data: