services:
  nginx:
    container_name: nginx-reborn
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - fastapi-reborn
    networks:
      - network-reborn

  fastapi-reborn:
    image: fastapi-reborn
    container_name: fastapi-reborn
    ports:
      - "8000:8000"
    networks:
      - network-reborn

networks:
  network-reborn: